[project]
name = "opencvplay"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.14"
dependencies = [
    "click>=8.3.1",
    "cupy-cuda13x>=13.6.0",
    "difpy>=4.2.1",
    "facedetector-py>=0.0.4",
    "filetype>=1.2.0",
    "mediapipe>=0.10.14",
    "numpy>=2.2.6",
    "opencv-python>=4.12.0.88",
    "pytest>=9.0.2",
    "requests>=2.32.5",
    "rich>=14.2.0",
    "scikit-learn>=1.8.0",
    "scipy>=1.16.3",
    "selenium>=4.38.0",
    "tensorflow>=2.14.0",
    "ultralytics>=8.3.228",
    "webdriver-manager>=4.0.2",
]
